In [1]:
import pandas as pd
import numpy as np

# Series
Създаваме series със сиответните стойности

In [2]:
series = pd.Series([10, 22, 34])

Можем да добавяме различни индекси

In [3]:
# series = pd.Series([10, 22, 34], index=["a", "b", "c"])

In [4]:
series

0    10
1    22
2    34
dtype: int64

In [5]:
series.values

array([10, 22, 34], dtype=int64)

In [6]:
series.index

RangeIndex(start=0, stop=3, step=1)

In [7]:
series.index.values

array([0, 1, 2], dtype=int64)

In [8]:
np.sum(series)

66

In [9]:
pd_series = pd.Series({'Ohio': 35000,'Texas': 71000,'Oregon': 16000})
print(pd_series)

Ohio      35000
Texas     71000
Oregon    16000
dtype: int64


In [10]:
my_dict = {'Sofia': 350003,'Varna': 710003,'Vidin': 160003}
dict_series_2 = pd.Series(my_dict)
print(dict_series_2)

Sofia    350003
Varna    710003
Vidin    160003
dtype: int64


Създаване на Series от друг съществуващ
Подаваме списък за индекси. Индексите, за които е открито съвпадение се наливат в новия series, тези които не са открити остават NaN.

In [11]:
# pd_series = pd.Series({'Ohio': 35000,
# 'Texas': 71000,
# 'Oregon': 16000})
states = ['California', 'Ohio', 'Texas']
new_series = pd.Series(pd_series, index=states)
print(new_series)

California        NaN
Ohio          35000.0
Texas         71000.0
dtype: float64


# DataFrame
Зареждане на данни от csv или какъвто и да е друг файл.
Една точка(./) преди пътя търси файла в текущата директория, а ако са две точkи(../) търси в горна директория.

In [12]:
# pd.read_csv("./data/somefile.csv")

Създаване на DataFrame

Създаване на дейтафрейм, ползвайки списък от списъци. Ако разполагаме с този списък, можем да подадем само името му.

In [13]:
dict = {
    'state': ['Ohio', 'Ohio', 'Nevada'],
    'year': [2000, 2002, 2001],
    'pop': [1.5, 3.6, 2.4]}
df_list = pd.DataFrame(dict)
df_list

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2002  3.6
2  Nevada  2001  2.4

In [14]:
df = pd.DataFrame([
    [4, 7, 10], 
    [5, 8, 11], 
    [6, 9, 12]],
index=[1, 2, 3],
columns=['a', 'b', 'c']) 
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

Извикване на колона от DataSet

Колоната може да бъде извикана по име

In [15]:
df.a

1    4
2    5
3    6
Name: a, dtype: int64

In [16]:
type(df.a)

pandas.core.series.Series

Препоръчва се този начин за извикване на колона, защото не създава проблем, ако има интервал в името ѝ.

In [17]:
df["a"]

1    4
2    5
3    6
Name: a, dtype: int64

Можем да достъпим и ред, по неговия индекс

In [18]:
df.iloc[1]

a     5
b     8
c    11
Name: 2, dtype: int64

### Копиране на дейтафрейм
Ако напишем "my_df = df", това не създава нов дейта фрейм, а създава променлива, която сочи към същия. Ако правим промени през нея, то те ще променят оригиналния дейта фрейм

In [19]:
my_df = df.copy()

In [20]:
my_df += 20 #променяме
my_df

a   b   c
1  24  27  30
2  25  28  31
3  26  29  32

In [21]:
df #Остава непроменен

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

### Ънпивотване - melt


In [22]:
pd.melt(df)
# pd.melt(df, value_name="Стйност", var_name="Име")

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

### Pivot

In [23]:
pd.pivot(df, columns='a')

b               c            
a    4    5    6     4     5     6
1  7.0  NaN  NaN  10.0   NaN   NaN
2  NaN  8.0  NaN   NaN  11.0   NaN
3  NaN  NaN  9.0   NaN   NaN  12.0

### Обединяване/долепяне
Обединяване/долепяне на два или повече дейта фреймове с една и съща структура.

In [24]:
df1 = pd.DataFrame( [
    [4, 7, 10], 
    [5, 8, 11], 
    [6, 9, 12]], 
    index=[1, 2, 3], 
    columns=[ 'a', 'b', 'c '])

In [25]:
df2 = pd.DataFrame( [
    [104, 107, 1010], 
    [105, 108, 1011], 
    [106, 109, 1012]], 
    index=[1, 2, 3], 
    columns=[ 'a', 'b', 'c '])

In [26]:
pd.concat([df1, df2])

a    b    c 
1    4    7    10
2    5    8    11
3    6    9    12
1  104  107  1010
2  105  108  1011
3  106  109  1012

Тъй като в горния пример се запазват индексите, можем да ги резетнем

In [27]:
df_concat = pd.concat([df1, df2])
df_concat.reset_index()

index    a    b    c 
0      1    4    7    10
1      2    5    8    11
2      3    6    9    12
3      1  104  107  1010
4      2  105  108  1011
5      3  106  109  1012

По същия начин можем да ги долепим по индекс, вместо по колона. 
И в двата случая, ако не мамери съвпадение, поставя стойности NaN.

In [28]:
pd.concat([df1, df2], axis=1)

a  b  c     a    b    c 
1  4  7  10  104  107  1010
2  5  8  11  105  108  1011
3  6  9  12  106  109  1012

### Сортиране
Със списък от колони ще сортира на много нива

In [29]:
df.sort_values(by="a", ascending=False)

a  b   c
3  6  9  12
2  5  8  11
1  4  7  10

### Изтриване на колона

In [30]:
df.drop(columns=["a"])

b   c
1  7  10
2  8  11
3  9  12

### Филтриране

In [31]:
df.b > 8

1    False
2    False
3     True
Name: b, dtype: bool

In [32]:
df[df.b > 8]

a  b   c
3  6  9  12

In [33]:
df[~(df.b > 8)]

a  b   c
1  4  7  10
2  5  8  11

### Най-големи и най-малки стойности TopN

In [34]:
df.nlargest(2, "a")

a  b   c
3  6  9  12
2  5  8  11

In [35]:
df.nsmallest(2, "a")

a  b   c
1  4  7  10
2  5  8  11

### Проверка за наличие на стойност

In [36]:
df.a.isin([4])

1     True
2    False
3    False
Name: a, dtype: bool

In [37]:
df[df.a.isin([4])]

a  b   c
1  4  7  10

In [38]:
df[df.a.isin([4, 6])]

a  b   c
1  4  7  10
3  6  9  12

### Избиране на ред и колона
iloc търси колона по индекс, а loc по име. Алтернативи са iat и at, но рядко се срещат в практиката.

In [39]:
df.iloc[1,1]

8

In [40]:
df.iloc[:,1]

1    7
2    8
3    9
Name: b, dtype: int64

In [41]:
df.iloc[1:2,1] #Може да се слайсва

2    8
Name: b, dtype: int64

In [42]:
df.iloc[1,:]

a     5
b     8
c    11
Name: 2, dtype: int64

In [43]:
df.loc[1,"a"]

4

In [44]:
df.loc[df.a < 6, "b"]

1    7
2    8
Name: b, dtype: int64

### Брой повторения на уникални стойности
Показва, че броя на 4-ките е 1, на 5 и на 6 също.
Използва се за категорийни променливи.

In [45]:
df.value_counts("a")

a
4    1
5    1
6    1
dtype: int64

### Брой редове и колони на дейтафрейма

In [46]:
df.shape

(3, 3)

### Уникални стойности

In [47]:
df.a.unique()

array([4, 5, 6], dtype=int64)

### Основни статистически данни за дейтасета

In [48]:
df.describe()

a    b     c
count  3.0  3.0   3.0
mean   5.0  8.0  11.0
std    1.0  1.0   1.0
min    4.0  7.0  10.0
25%    4.5  7.5  10.5
50%    5.0  8.0  11.0
75%    5.5  8.5  11.5
max    6.0  9.0  12.0

In [49]:
df.a.max() #могат да се ползват и статистическите функции

6

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


### Обработка на липсващи данни

In [50]:
df_nan = pd.DataFrame(
    [[np.nan, .7, 10], 
     [5, None, 11], 
     [pd.NaT, 9, np.nan]], 
    index= [1, 2, 3], 
    columns=['a', 'b', 'c']) 


In [51]:
df_nan

a    b     c
1  NaN  0.7  10.0
2    5  NaN  11.0
3  NaT  9.0   NaN

In [52]:
df_nan.isna()

a      b      c
1   True  False  False
2  False   True  False
3   True  False   True

In [53]:
df_nan.isnull()

a      b      c
1   True  False  False
2  False   True  False
3   True  False   True

In [54]:
df_nan.fillna("Empty")

a      b      c
1  Empty    0.7   10.0
2      5  Empty   11.0
3  Empty    9.0  Empty

In [55]:
df_nan.dropna()

Empty DataFrame
Columns: [a, b, c]
Index: []

In [56]:
df_nan.dropna(how="all")

a    b     c
1  NaN  0.7  10.0
2    5  NaN  11.0
3  NaT  9.0   NaN

### Дублирани данни

In [57]:
df_duplicates = pd.DataFrame([
    [7, 7, 7], 
    [7, 7, 7], 
    [7, 7, 7]], 
    index=[1, 2, 3], 
    columns=['a', 'b', 'c']) 

In [58]:
df_duplicates

a  b  c
1  7  7  7
2  7  7  7
3  7  7  7

Засича първия ред, като не дублиран, защото го намира за първи път

In [59]:
df_duplicates.duplicated()

1    False
2     True
3     True
dtype: bool

### Агрегиране и групиране

In [60]:
df_for_grouping = pd.DataFrame({
    'key1' : ['a', 'a', 'b', 'b', 'a'],
    'key2' : ['one', 'two', 'one', 'two', 'one'],
    'data1' : [2, 4, 7, 1, 3],
    'data2' : [3, 2, 1, 4, 7]})

In [65]:
df_for_grouping

key1 key2  data1  data2
0    a  one      2      3
1    a  two      4      2
2    b  one      7      1
3    b  two      1      4
4    a  one      3      7

In [66]:
grouped = df_for_grouping['data1'].groupby(df_for_grouping['key1'])

In [67]:
print(grouped.mean())

key1
a    3.0
b    4.0
Name: data1, dtype: float64
